export const siteConfig = {
  name: "SEVCONT GLOBAL",
  legalName: "SEVCONT GLOBAL CO., LIMITED",
  tagline: "Connecting Markets. Delivering Solutions.",
  description:
    "Global industrial sourcing and engineering solutions. SEVCONT connects businesses with trusted manufacturers across Asia while delivering engineering expertise, logistics excellence, and turnkey industrial solutions across power systems, raw materials, and infrastructure.",
  url: "https://www.sevcont.com",
  email: "info@sevcont.com",
  phone: "+852 0000 0000",
  social: {
    linkedin: "https://www.linkedin.com/company/sevcont",
    whatsapp: "https://wa.me/85200000000",
  },
  markets: [
    {
      name: "Hong Kong",
      code: "HK",
      lat: 22.3193,
      lng: 114.1694,
      live: true,
      blurb: "Regional trading hub — sourcing, certification, and finance coordination.",
      projects: 12,
      partners: 24,
      services: ["Trading & Certification", "Logistics", "Engineering"],
    },
    {
      name: "China",
      code: "CN",
      lat: 31.2304,
      lng: 121.4737,
      live: true,
      blurb: "Manufacturing base across power equipment, steel, and industrial components.",
      projects: 31,
      partners: 48,
      services: ["Power Systems", "Raw Materials", "Manufacturing QA"],
    },
    {
      name: "Saudi Arabia",
      code: "SA",
      lat: 24.7136,
      lng: 46.6753,
      live: true,
      blurb: "Delivered power and solar projects supporting national infrastructure.",
      projects: 9,
      partners: 15,
      services: ["Power Systems", "Solar & BESS", "Engineering"],
    },
    {
      name: "Egypt",
      code: "EG",
      lat: 30.0444,
      lng: 31.2357,
      live: true,
      blurb: "Structural steel and industrial materials supply for construction programs.",
      projects: 14,
      partners: 19,
      services: ["Raw Materials", "Logistics", "Construction Supply"],
    },
    {
      name: "Rwanda",
      code: "RW",
      lat: -1.9403,
      lng: 29.8739,
      live: true,
      blurb: "Standby and hybrid power deployment across national infrastructure sites.",
      projects: 7,
      partners: 11,
      services: ["Power Systems", "Engineering", "Training"],
    },
    {
      name: "Kenya",
      code: "KE",
      lat: -1.2921,
      lng: 36.8219,
      live: false,
      blurb: "Future market — expansion planned for 2027.",
      projects: 0,
      partners: 0,
      services: [],
    },
    {
      name: "Nigeria",
      code: "NG",
      lat: 9.082,
      lng: 8.6753,
      live: false,
      blurb: "Future market — expansion planned for 2027.",
      projects: 0,
      partners: 0,
      services: [],
    },
    {
      name: "UAE",
      code: "AE",
      lat: 24.4539,
      lng: 54.3773,
      live: false,
      blurb: "Future market — expansion planned for 2027.",
      projects: 0,
      partners: 0,
      services: [],
    },
  ],
} as const;

export const navigation = [
  {
    label: "About Us",
    href: "/about",
    children: [
      { label: "Company Profile", href: "/about#profile" },
      { label: "Our Mission", href: "/about#mission" },
      { label: "Our Vision", href: "/about#vision" },
      { label: "Why SEVCONT", href: "/about#why" },
      { label: "Global Presence", href: "/about#presence" },
    ],
  },
  {
    label: "Services & Solutions",
    href: "/services",
    children: [
      { label: "Power Systems", href: "/services#power-systems" },
      { label: "Industrial Raw Materials", href: "/services#raw-materials" },
      { label: "Engineering Services", href: "/services#engineering" },
      { label: "Logistics & Supply Chain", href: "/services#logistics" },
    ],
  },
  {
    label: "Industries",
    href: "/industries",
    children: [
      { label: "Construction", href: "/industries#construction" },
      { label: "Manufacturing", href: "/industries#manufacturing" },
      { label: "Oil & Gas", href: "/industries#oil-gas" },
      { label: "Infrastructure", href: "/industries#infrastructure" },
      { label: "Government Projects", href: "/industries#government" },
    ],
  },
  {
    label: "Projects",
    href: "/projects",
    children: [
      { label: "Case Studies", href: "/projects#case-studies" },
      { label: "Delivered Projects", href: "/projects#delivered" },
      { label: "Countries Served", href: "/projects#countries" },
    ],
  },
  { label: "Suppliers", href: "/suppliers" },
  {
    label: "Insights",
    href: "/insights",
    children: [
      { label: "Articles", href: "/insights#articles" },
      { label: "Market Updates", href: "/insights#market-updates" },
      { label: "Technical Guides", href: "/insights#technical-guides" },
    ],
  },
  {
    label: "Downloads",
    href: "/downloads",
    children: [
      { label: "Company Profile", href: "/downloads#company-profile" },
      { label: "Brochures", href: "/downloads#brochures" },
      { label: "Catalogues", href: "/downloads#catalogues" },
    ],
  },
  { label: "Contact", href: "/contact" },
] as const;

export const footerNav = {
  company: [
    { label: "About Us", href: "/about" },
    { label: "Industries", href: "/industries" },
    { label: "Projects", href: "/projects" },
    { label: "Suppliers", href: "/suppliers" },
  ],
  solutions: [
    { label: "Power Systems", href: "/services#power-systems" },
    { label: "Industrial Raw Materials", href: "/services#raw-materials" },
    { label: "Engineering Services", href: "/services#engineering" },
    { label: "Logistics & Supply Chain", href: "/services#logistics" },
  ],
  resources: [
    { label: "Insights", href: "/insights" },
    { label: "Downloads", href: "/downloads" },
    { label: "Request a Quote", href: "/rfq" },
  ],
} as const;
